apiVersion: v1
kind: Namespace
metadata:
  name: evmon
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: evmon
  namespace: evmon
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: evmon-cluster-role
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["evmon.centerionware.com"]
    resources: ["evmonendpoints"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: evmon-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: evmon
    namespace: evmon
roleRef:
  kind: ClusterRole
  name: evmon-cluster-role
  apiGroup: rbac.authorization.k8s.io